<?php
// auto-generated by sfPropelCrud
// date: 2007/11/24 12:45:00
?>
<?php use_helper('Object') ?>

<?php echo form_tag('organization/update') ?>

<?php echo object_input_hidden_tag($organization, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($organization, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Organization type:</th>
  <td><?php echo object_select_tag($organization, 'getOrganizationTypeId', array (
  'related_class' => 'OrganizationType',
  'include_blank' => true,
)) ?></td>
</tr>

<tr>
  <th>Country:</th>
  <td><?php echo object_input_tag($organization, 'getCountry', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Home page:</th>
  <td><?php echo object_input_tag($organization, 'getHomePage', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Research keywords:</th>
  <td><?php echo object_input_tag($organization, 'getResearchKeywords', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Research description:</th>
  <td><?php echo object_textarea_tag($organization, 'getResearchDescription', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($organization->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'organization/delete?id='.$organization->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('show', 'organization/show?id='.$organization->getId()) ?>
<?php else: ?>
<?php endif; ?>
  &nbsp;<?php echo link_to('list organizations', 'organization/list') ?>

</form>
