<?php
// auto-generated by sfPropelCrud
// date: 2007/11/25 00:34:09
?>
<h1>Collaborations</h1>
<?php echo link_to ('Create Collaboration', 'collaboration/create') ?>
<table class='list'>
<thead>
<tr>
  <th>Name</th>
  
  <th>&nbsp;</th>  
</tr>
</thead>
<tbody>
<?php $i=1;  
foreach ($collaborations as $collaboration): ?>
<tr class='record <?php if (fmod(++$i, 2) ) : ?>even-record <?php endif;?>'>
    <td><?php echo link_to($collaboration->getName(), 'collaboration/show?id='.$collaboration->getId()) ?></td>
      <td><?php echo link_to("edit",'collaboration/edit?id='.$collaboration->getId()) ?>&nbsp;
          <?php echo link_to("delete",'collaboration/delete?id='.$collaboration->getId(),
                               array('confirm' => 'Are you sure?')) ?></td>             
  </tr>
<?php endforeach; ?>
</tbody>
</table>


