<?php
// auto-generated by sfPropelCrud
// date: 2007/11/24 12:45:00
?>
<h1>Organizations</h1>
<?php echo link_to ('Create Organization', 'organization/create') ?>

<table class='list'>
<thead>
<tr>
  <th>Name</th>
  <th>Country</th>
  <th>Organization type</th>
  <th>Home page</th>
  <th>Researchers Count</th>
  <th>Research keywords</th>
  <th>Research description</th>
</tr>
</thead>
<tbody>
<?php $i=1; 
  foreach ($organizations as $organization): 
?>
<tr class='record <?php if (fmod(++$i, 2) ) : ?>even-record <?php endif;?>  '> 
      <td><?php echo link_to($organization->getName(),'organization/show?id='.$organization->getId()) ?></td>
      <td><?php echo $organization->getCountry() ?></td>
      <td><?php echo $organization->getOrganizationType()->getName() ?></td>
      <td><?php echo $organization->getHomePage() ?></td>
      <td><?php echo $organization->countResearchers() ?></td>
      <td><?php echo $organization->getResearchKeywords() ?></td>
      <td><?php echo $organization->getResearchDescription() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

