default:
  http_metas:
    content-type: text/html

  metas:
    title:        MyIsern Web Interface
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [isern]

  javascripts:    []

  has_layout:     on
  layout:         layout
