<?php
// auto-generated by sfPropelCrud
// date: 2007/11/24 12:45:12
?>
<?php use_helper('Object') ?>

<?php echo form_tag('researcher/update') ?>

<?php echo object_input_hidden_tag($researcher, 'getId') ?>
<?php if ($sf_request->hasErrors()): ?>  
  <div id="errors" style="padding:10px;">
    Please correct the following errors and resubmit:
    <ul>
    <?php foreach ($sf_request->getErrors() as $error): ?>
      <li><?php echo $error ?></li>
    <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>

<table>
<tbody>
<tr>
  <th>Organization:</th>
  <td><?php echo object_select_tag($researcher, 'getOrganizationId', array (
  'related_class' => 'Organization',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($researcher, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($researcher, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Picture link:</th>
  <td><?php echo object_input_tag($researcher, 'getPictureLink', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Bio statement:</th>
  <td><?php echo object_textarea_tag($researcher, 'getBioStatement', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($researcher->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'researcher/delete?id='.$researcher->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'researcher/show?id='.$researcher->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'researcher/list') ?>
<?php endif; ?>
</form>
