<?php
// auto-generated by sfPropelCrud
// date: 2007/11/24 12:45:12
?>
<h1>Researchers</h1>
<?php echo link_to ('Create Researchers', 'researcher/create') ?>

<table class='list'>
<thead>
<tr>
  <th>Name</th>
  <th>Organization</th>
  <th>Email</th>
  <th>Picture link</th>
  <th>Bio statement</th>
  <th>&nbsp;</th>    
</tr>
</thead>
<tbody>

<?php 
$i=1;
foreach ($researchers as $researcher): ?>
<tr  class='record <?php if (fmod(++$i, 2) ) : ?>even-record <?php endif;?>' >
      <td><?php echo link_to($researcher->getName(), 'researcher/show?id='.$researcher->getId()) ?></td>
      <td><?php echo $researcher->getOrganization() ?></td>
      <td><?php echo $researcher->getEmail() ?></td>
      <td><?php echo $researcher->getPictureLink() ?></td>
      <td><?php echo $researcher->getBioStatement() ?></td>
      <td><?php echo link_to("edit",'researcher/edit?id='.$researcher->getId()) ?>&nbsp;
          <?php echo link_to("delete",'researcher/delete?id='.$researcher->getId(), 
          			            array('confirm' => 'Are you sure?')) ?></td>          
  </tr>
<?php endforeach; ?>
</tbody>
</table>

