<?php
// auto-generated by sfPropelCrud
// date: 2007/11/24 12:45:12
?>
<h1>View Researcher</h1>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $researcher->getId() ?></td>
</tr>
<tr>
<th>Organization: </th>
<td><?php echo link_to($researcher->getOrganization() , 'organization/show?id=' . $researcher->getOrganizationId()  ) ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $researcher->getName() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $researcher->getEmail() ?></td>
</tr>
<tr>
<th>Picture link: </th>
<td><?php echo $researcher->getPictureLink() ?></td>
</tr>
<tr>
<th>Bio statement: </th>
<td><?php echo $researcher->getBioStatement() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $researcher->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'researcher/edit?id='.$researcher->getId()) ?>
&nbsp;<?php echo link_to('list', 'researcher/list') ?>
