<?php
// auto-generated by sfPropelCrud
// date: 2007/11/24 12:47:36
?>
<?php use_helper('Object') ?>

<?php echo form_tag('organization_type/update') ?>

<?php echo object_input_hidden_tag($organization_type, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($organization_type, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($organization_type->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'organization_type/delete?id='.$organization_type->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'organization_type/show?id='.$organization_type->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'organization_type/list') ?>
<?php endif; ?>
</form>
