<?php
// auto-generated by sfPropelCrud
// date: 2007/11/24 12:47:36
?>
<h1>organization_type</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
</tr>
</thead>
<tbody>
<?php foreach ($organization_types as $organization_type): ?>
<tr>
    <td><?php echo link_to($organization_type->getId(), 'organization_type/show?id='.$organization_type->getId()) ?></td>
      <td><?php echo $organization_type->getName() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'organization_type/create') ?>
