<?php
// auto-generated by sfPropelCrud
// date: 2007/11/24 12:47:36
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $organization_type->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $organization_type->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'organization_type/edit?id='.$organization_type->getId()) ?>
&nbsp;<?php echo link_to('list', 'organization_type/list') ?>
