all:
  propel:
    class:          sfPropelDatabase
    param:
      phptype: mysql
      host: localhost
      database: isern_production
      username: isern
      password: password_change_me
dev:
  propel:
    class:      sfPropelDatabase
    param:
      phptype: mysql
      host: localhost
      database: isern_development
      username: isern
      password: password_change_me
test:
  propel:
    class:      sfPropelDatabase
    param:
      phptype: mysql
      host: localhost
      database: isern_test
      username: isern
      password: password_change_me
