<?php
// auto-generated by sfPropelCrud
// date: 2007/11/25 00:34:09
?>
<?php use_helper('Object') ?>
<?php if ($collaboration->getId() ) : ?>
<h1>Edit Collaboration</h1>
<?php else : ?> 
<h1>Create Collaboration</h1>
<?php endif; ?>

<?php echo form_tag('collaboration/update') ?>

<?php echo object_input_hidden_tag($collaboration, 'getId') ?>
<?php if ($sf_request->hasErrors()): ?>
  <div id="errors" style="padding:10px;">
    Please correct the following errors and resubmit:
    <ul>
    <?php foreach ($sf_request->getErrors() as $error): ?>
      <li><?php echo $error ?></li>
    <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>


<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($collaboration, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th valign='top'>Description:</th>
  <td><?php echo object_textarea_tag($collaboration, 'getDescription', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th  valign='top'>Organizations:</th>
  <td><?php echo select_tag('collaboratingOrganizations', options_for_select($options,$collaboratingOrganizationIds),array('multiple' => true)) ?></td>
</tr>
<tr>
  <th valign='top'>Years:</th>
  <td>
<?php  
   for ($year = 1990; $year < 2011; $year++) { ?>
     	
<?php echo checkbox_tag("collaborationYears[$year]", $year, in_array($year, $collaborationYears)  )  ?> <?php echo $year ?> 
     <? if (!( ($year+1)%5)) { ?> <br /> <? } ?>   
<?php } ?> 
  </td>
</tr>
<tr>
  <th valign='top'>Outcome Types:</th>
  <td>
<?php  
    $outcomeTypes = $collaboration->getCollaborationOutcomeTypes();
   for ($i = 0; $i < 5; $i++) { 
   	 $value = "";
     if (array_key_exists($i, $outcomeTypes) ) { 
       $value =   $outcomeTypes[$i]->getOutcomeType() ;
     }
     echo input_tag("collaborationOutcomeTypes[$i]", $value) . "<br />";   
   } 
?> 
  </td>
<tr>
  <th valign='top'>Collaboration Types:</th>
  <td>
<?php  
    $CollaborationTypes = $collaboration->getCollaborationTypes();
   for ($i = 0; $i < 5; $i++) { 
   	 $value = "";
     if (array_key_exists($i, $CollaborationTypes) ) { 
       $value =   $CollaborationTypes[$i]->getCollaborationType() ;
     }
     echo input_tag("collaborationTypes[$i]", $value) . "<br />";   
   } 
?> 
  </td>  
</tr>   


</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($collaboration->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'collaboration/delete?id='.$collaboration->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'collaboration/show?id='.$collaboration->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'collaboration/list') ?>
<?php endif; ?>
</form>
