<?php
// auto-generated by sfPropelCrud
// date: 2007/11/25 00:34:09
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $collaboration->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $collaboration->getName() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $collaboration->getDescription() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'collaboration/edit?id='.$collaboration->getId()) ?>
&nbsp;<?php echo link_to('list', 'collaboration/list') ?>
